# fly.toml app configuration file generated for borjankalinoski on 2023-06-17T14:45:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "borjankalinoski"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
source = "data"
destination = "/data"
